import fs from "node:fs"

const tjp = fs.readFileSync("./src/external/tigerjython-parser-worker.js", {encoding: "utf8"})

const tjpstring = tjp.replaceAll("\\", "\\\\").replaceAll("`", "\\`")

const content = `// do not edit this file\nexport const tjpWorkerString: string = \`${tjpstring}\``

fs.writeFileSync("./src/inlinedTJP.ts", content, {encoding: "utf8"})